### ISSUE TITLE
Usable Iron Trapdoors

### ISSUE THREAD

**Issue by minijaham** [MihaiChirculete/WorldGuard#183]
**Describe the bug**
Never mind bruh I fixed it myself. You guys forgot to put the ID on "const USABLES" 
Might wanna fix that m8

**Comment by suerion** [comment]
thanks for this, i will look on it, i would add the id's in futures

**Comment by minijaham** [comment]
No problem xD if you don't have time, I can make a pull request for you

**Comment by suerion** [comment]
Yeah, i will try it tomorow, or you coul add an pull. Thanks

**Comment by suerion** [comment]
so fixed with merge ;)
