### ISSUE TITLE
How exactly does "priority" flag work?

### ISSUE THREAD

**Issue by minijaham** [MihaiChirculete/WorldGuard#187]
This is not a bug. However, the priority option in the code doesn't seem to work, no matter what I do.

The expected behavior is that a priority region with a smaller integer should override other regions.

But in my case, it didn't work.

**Comment by minijaham** [comment]
Nevermind. I've fixed the issue

**Comment by suerion** [comment]
? Huh? Priority does work normal

the region with the higher priority does override the lower
