### ISSUE TITLE
File regions.yml Editing

### ISSUE THREAD

**Issue by minijaham** [MihaiChirculete/WorldGuard#188]
**Is your feature request related to a problem? Please describe.**
Yes. This feature is requested due to a problem I have. The edits I make in the regions.yml doesn't save after a restart.

**Describe the solution you'd like**
I wish if regions.yml could be edited and is saved after restart.

**Describe alternatives you've considered**
You can still edit these in-game, but it's really inefficient.

**Comment by suerion** [comment]
You could edit the region.yml file afte the first region was created, had you tried it?

**Comment by minijaham** [comment]
What do you mean the first region?

I currently have 30+ regions. They are all not editable

**Comment by minijaham** [comment]
And the "priority" option isn't really working fluently as expected. It seems like it's working sometimes, but not all the time.

**Comment by suerion** [comment]
Stop your server, edit the region file, start the server again, this would be work fine

the priority is allways working fine, the higher priority overwrite the lower one.

could you say me, whats your plugins, whats your worldguard version, what your server version do you have?

We need please more informations, for me it work all, what for you doesn't work, please try to use the form for issues

**Comment by minijaham** [comment]
I am currently using WorldGuard v1.1.7

And the server version is #1815, which I believe is the second to latest version of PMMP

I'll try the solution you've provided. If it doesn't work, I'll contact back. Thank you :)

**Comment by suerion** [comment]
We save the region file if the server stopped by crash, if you had changed it, before you stopped the server, it overwrites the region file with the actuall settings, do never /reload on pmmp.

if you want to change it, you need to stop the server before.

**Comment by minijaham** [comment]
Thank you so much! I've stopped the server, and it worked.

Thank you for your fast response. I appreciate it!
