### ISSUE TITLE
Effects cleared when entering new region

### ISSUE THREAD

**Issue by minijaham** [MihaiChirculete/WorldGuard#189]
**Describe the bug**
Effects you previously had gets removed when you enter a new region.

**To Reproduce**
1. Have effects on
2. Enter a new region

**Expected behavior**
Effects should NOT clear

**Comment by suerion** [comment]
We know about this bug, it will be fixed in #185 

but it is not finished yet

**Comment by minijaham** [comment]
Never mind...I fixed it myself lol Thank you for notifying me that the code exists.
