### ISSUE TITLE
Hammer glitch #bug

### ISSUE THREAD

**Issue by RebelCraft19** [MihaiChirculete/WorldGuard#190]
Hello, 
We found a bug. When we use a hammer plugin we can break the blocks in the spawn, even if it is protected. Please pay it.
Rebel

**Comment by awgybop1** [comment]
Hello, I will look into your issue, but I am not sure if it is something that we can directly fix since we are just cancelling the events. If hammer is ignoring the fact the event is cancelled, there isn't anything we can do to directly fix it.

**Comment by RebelCraft19** [comment]
Hello,Ok, I understand the problem.  Thanks for your time.Envoyé depuis mon appareil mobile Samsung.
-------- Message d'origine --------De : Austin <notifications@github.com> Date : 12/10/2020  18:30  (GMT+01:00) À : MihaiChirculete/WorldGuard <WorldGuard@noreply.github.com> Cc : RebelCraft19 <gouin.gabriel@free.fr>, Author <author@noreply.github.com> Objet : Re: [MihaiChirculete/WorldGuard] Hammer glitch #bug (#190) 
Hello, I will look into your issue, but I am not sure if it is something that we can directly fix since we are just cancelling the events. If hammer is ignoring the fact the event is cancelled, there isn't anything we can do to directly fix it.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MihaiChirculete/WorldGuard/issues/190#issuecomment-707222766",
"url": "https://github.com/MihaiChirculete/WorldGuard/issues/190#issuecomment-707222766",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by awgybop1** [comment]
Can't fix this issue - it's a problem with the Hammer plugin itself not checking if the break event was cancelled.
