### ISSUE TITLE
break block permission doesnt work?

### ISSUE THREAD

**Issue by GloomyBumy** [MihaiChirculete/WorldGuard#191]
**Describe the bug**
I am running into a problem where it doesnt let me break any block even though i set it to true (it only works if im op and other permission works fine eccept breaking blocks).I have two world plugin which is worldguard and worlds Idk which plugins created the problem. pls help.

**Expected behavior**
i am making a small prison server and i expect it to let me break block in certain area where breaking is enabled.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [ i code on macos but i join with minecraft on my ipad ]
 - Browser [chrome]
 - Version [version of the plugin? it is 1.1.7]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by awgybop1** [comment]
1. Does this issue still occur with WorldGuard removed?
2. Is the option "spawn-protection" in your server.properties set to a value above 0?

**Comment by UnEnanoMas** [comment]
@awgybop1 

https://youtu.be/0bXHeAYt0As

**Comment by suerion** [comment]
What version do you use?

**Comment by suerion** [comment]
> **Describe the bug**
> I am running into a problem where it doesnt let me break any block even though i set it to true (it only works if im op and other permission works fine eccept breaking blocks).I have two world plugin which is worldguard and worlds Idk which plugins created the problem. pls help.
> 
> **Expected behavior**
> i am making a small prison server and i expect it to let me break block in certain area where breaking is enabled.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [ i code on macos but i join with minecraft on my ipad ]
> * Browser [chrome]
> * Version [version of the plugin? it is 1.1.7]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context**
> Add any other context about the problem here.

Why do you use 2 Protecting plugins. It would cause problems, use only worlds or use only worldguard and multiworld. I think, worlds is to loaded with features, but you have to decide, don‘t use both at the same time

**Comment by GloomyBumy** [comment]
Everything is good now I uninstalled some plugins and it now work again.
