### ISSUE TITLE
is there a way to make it doesnt say "you cant break block in this region"? if a player break a block it message pop up in chat and it kind of fill up the chat too much

### ISSUE THREAD

**Issue by GloomyBumy** [MihaiChirculete/WorldGuard#195]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by suerion** [comment]
In the next update, you could stop the message with an flag 

#194 please wait for 1.1.8
