### ISSUE TITLE
Custom enchants stop working while we change worldguard area

### ISSUE THREAD

**Issue by RealBJsingh** [MihaiChirculete/WorldGuard#197]
**Describe the bug**
While we change area from one worldguard area to another all custom enchants stop working .
(Piggy custom enchants)
**To Reproduce**
=> To reproduce it we need to remove armour and rewear it.

I hope I have given whole information and it would be fixed soon thank u !!!

**Comment by awgybop1** [comment]
Not exactly sure what you mean, but I'll see what I can find - and if anything I will be sure to fix it!

**Comment by suerion** [comment]
Please try this problem with the newest updated, after it is released on Poggit

**Comment by suerion** [comment]
Please try to test the new version, and come back to me

**Comment by RealBJsingh** [comment]
Ok

**Comment by suerion** [comment]
Issue cleared ;)
