### ISSUE TITLE
Try to add on and off button for messages shown through worldguard in config

### ISSUE THREAD

**Issue by RealBJsingh** [MihaiChirculete/WorldGuard#198]
**Is your feature request related to a problem? Please describe.**
Whenever I try to remove messages shown through worldguard like'You can break block in this area' they doesn't works

**Describe the solution you'd like**
If you add a on or off option in config or message.yml for messages shown by worldguard will be very good

**Comment by awgybop1** [comment]
I can add a check for if they messages are blank or have text such as "off" so that they won't show up, but there is a flag to disable all the messages for right now if you'd like to use it.
You can use **/rg flag set (region) deny-msg false**

**Comment by suerion** [comment]
it is in the GUI also to enable and disable,

But the permission messages, we need to change also.

**Comment by suerion** [comment]
Update is released, please try the toggle in the gui and come back here

**Comment by suerion** [comment]
Issue or suggestion cleared
