### ISSUE TITLE
UI Error

### ISSUE THREAD

**Issue by xKurt** [MihaiChirculete/WorldGuard#206]
![C0507DC6-DDFA-4D1F-A31D-C2ABA3F279E8](https://user-images.githubusercontent.com/65582746/104799449-2c3c5200-580a-11eb-8711-9cab2183517e.png)
In the UI, I clicked manage existing regions button and it shows this

**Comment by suerion** [comment]
Hello, thanks for adding this issue.

it is for us an known issue. I have write in discord how to solve this problem.

it is an problem in the region file, if you write only numbers in the name. Please stop the server, change in the region.yml file the names of the regions to an name, please not use only numbers. then start the server again.

it should work

**Comment by dev-ste** [comment]
> Hello, thanks for adding this issue.
> 
> it is for us an known issue. I have write in discord how to solve this problem.
> 
> it is an problem in the region file, if you write only numbers in the name. Please stop the server, change in the region.yml file the names of the regions to an name, please not use only numbers. then start the server again.
> 
> it should work
@suerion 

I've solved this in [Pull Request 208](https://github.com/MihaiChirculete/WorldGuard/pull/208) 😄

**Comment by suerion** [comment]
should be resolved with @dev-ste #208
