### ISSUE TITLE
Not leave region bug

### ISSUE THREAD

**Issue by Sulfuritium** [MihaiChirculete/WorldGuard#207]
**Describe the bug**
We connect to the spawn and we go to our island with the / is go command and as soon as we are TP, we have 1/2 to be sent in the air with the message "You cannot get out of this zone ", so as soon as you fall back, you die.

**To Reproduce**
1. Go to connect to the server
2. Do /is go
3. We're thrown in the air and we die

**Expected behavior**
We expected to just be TP at our island and not fly away

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Vivaldi
 - Version 3.5

**Comment by suerion** [comment]
Do you have enabled the region leaving flag?

**Comment by Sulfuritium** [comment]
Yes, to prevent players from going out but not from dying when they want to go and play on their island

**Comment by suerion** [comment]
Thanks, we are looking on this.
