### ISSUE TITLE
WorldGuard Doesn't Load In Pocketminemp Server

### ISSUE THREAD

**Issue by rodjsid2** [MihaiChirculete/WorldGuard#212]
I downloaded the worldguard plugin from [this website](https://poggit.pmmp.io/p/WorldGuard) and putted the file into my plugins folder. However, it didn't work. It didn't say: 'Loaded WorldGuard' or something like that. I can't execute worldguard commands because of this. Can someone please help me? If you need any fursther information, please contact me. 

Maybe Usefull to know:
I am using a pocketmine 3.19.0;

**Comment by suerion** [comment]
How do you added the plugin? No one has problems with world guard adding pocketmine

**Comment by rodjsid2** [comment]
> 
> 
> How do you added the plugin? No one has problems with world guard adding pocketmine

I just download the file and upload it in the 'plugins;  folder.

**Comment by suerion** [comment]
Do you added the phar file? Or do you added the source folder?

**Comment by rodjsid2** [comment]
I added the .phar file.

**Comment by suerion** [comment]
please send me the log file

**Comment by rodjsid2** [comment]
> 
> 
> please send me the log file

No, then you can see my IP adress, but I have this error tho:
`Could not load plugin 'WorldGuard': Incompatible network protocol version (plugin requires one of: 428)`

What can I do about this?

**Comment by suerion** [comment]
You could use the newest version of pocketmine. It is not an bug of pocketmine, it is an update problem of minecraft himself

**Comment by rodjsid2** [comment]
> 
> 
> You could use the newest version of pocketmine. It is not an bug of pocketmine, it is an update problem of minecraft himself


Ok, thank you!
