### ISSUE TITLE
They Can Interact with Item Frame

### ISSUE THREAD

**Issue by EarlGarciaYT** [MihaiChirculete/WorldGuard#213]
**Describe the bug**
They can interact with item frame they can get the item in item frame even the place is guarded.

**Smartphone (please complete the following information):**
 - Device: Oppo A5s
 - OS: Android 8
 - Browser: Chrome
 - Version: IDK

**Additional context**

**Comment by suerion** [comment]
This is not a bug, !!! You need the addon from Hero Team. look on poggit
