### ISSUE TITLE
Bug plugin data region.yml

### ISSUE THREAD

**Issue by Willtom999** [MihaiChirculete/WorldGuard#217]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Hello I would like to tell you that there is a bug that when I put my region in your plugin update and I restart my server, it removes the one I replaced with a new one with no region I would like to solve the problem quickly please

**Comment by awgybop1** [comment]
Hello,

This might be related to a save issue, however the saving system has been changed since your issue was published, and as this issue is old, I am going to close it. If you are still experiencing this, please re-open an issue. Thanks :)
