### ISSUE TITLE
Update this plugins to 1.17.30 also 3.23.1

### ISSUE THREAD

**Issue by FachriPlayz** [MihaiChirculete/WorldGuard#232]
Update the plugins to 1.17.30 and 3.23.1 pmmp now pls i waited long time cmon its not that hard to update

**Comment by suerion** [comment]
Please open your eyes, it is released on github

**Comment by FachriPlayz** [comment]
Are you sure about that its doest support 3.23.1 dude update this plugins

**Comment by suerion** [comment]
it is updatet, is was your failure, not to see it

https://github.com/MihaiChirculete/WorldGuard/releases/tag/1.1.95-nopog

**Comment by FachriPlayz** [comment]
Its not updated if it is it will show this date September but its not its just 1.1.95 update this bro its taking so long

**Comment by suerion** [comment]
We will not update this on poggit! Go on and look on the releases side, there is your *.phar file! If you din‘t understand, how it would work, then learn to use github. It is not our problem. It is updated for „non poggit“ using without MCPE protocoll. 

Some fun fact, if there is a problem with the update from Minecraft, pocketmine development could take longer as a few days.
