### ISSUE TITLE
Bug still not working on 3.23.1 make a new update for this! September one make it.

### ISSUE THREAD

**Issue by FachriPlayz** [MihaiChirculete/WorldGuard#236]
Bug 3.23.1 error protocol 488 it still doest accept make a new update of September plz i been waiting for so god damn long.

**Comment by suerion** [comment]
i will ban you here, if if you would spam our issue tracker without right issues!!

https://github.com/MihaiChirculete/WorldGuard/releases/tag/1.1.95-nopog

use the Phar, we will not updatet to Poggit now!
