### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by logannn61** [MihaiChirculete/WorldGuard#292]
**Describe the bug**
The server crashed

**To Reproduce**
I dont know it just randomly happened

**Expected behavior**
Not to crash

30.04 02:35:33 [Server] CRITICAL TypeError: "pocketmine\\math\\Vector3::subtract(): Argument #1 ($x) must be of type int|float, pocketmine\\entity\\Location given, called in phar:///plugins/WorldGuard_pr-263.phar/src/MihaiChirculete/WorldGuard/EventListener.php on line 343" (EXCEPTION) in "pmsrc/vendor/pocketmine/math/src/Vector3" at line 84
30.04 02:35:33 [Server] INFO --- Stack trace ---
30.04 02:35:33 [Server] INFO #0 plugins/WorldGuard_pr-263.phar/src/MihaiChirculete/WorldGuard/EventListener(343): pocketmine\\math\\Vector3->subtract(object pocketmine\\entity\\Location#235449)
30.04 02:35:33 [Server] INFO #1 pmsrc/src/event/RegisteredListener(75): MihaiChirculete\\WorldGuard\\EventListener->onMove(object pocketmine\\event\\player\\PlayerMoveEvent#222910)
30.04 02:35:33 [Server] INFO #2 pmsrc/src/event/Event(62): pocketmine\\event\\RegisteredListener->callEvent(object pocketmine\\event\\player\\PlayerMoveEvent#222910)
30.04 02:35:33 [Server] INFO #3 pmsrc/src/player/Player(1237): pocketmine\\event\\Event->call()
30.04 02:35:33 [Server] INFO #4 pmsrc/src/player/Player(1324): pocketmine\\player\\Player->processMostRecentMovements()
30.04 02:35:33 [Server] INFO #5 pmsrc/src/world/World(881): pocketmine\\player\\Player->onUpdate(integer 18244)
30.04 02:35:33 [Server] INFO #6 pmsrc/src/world/World(807): pocketmine\\world\\World->actuallyDoTick(integer 18244)
30.04 02:35:33 [Server] INFO #7 pmsrc/src/world/WorldManager(362): pocketmine\\world\\World->doTick(integer 18244)
30.04 02:35:33 [Server] INFO #8 pmsrc/src/Server(1776): pocketmine\\world\\WorldManager->tick(integer 18244)
30.04 02:35:33 [Server] INFO #9 pmsrc/src/Server(1658): pocketmine\\Server->tick()
30.04 02:35:33 [Server] INFO #10 pmsrc/src/Server(1047): pocketmine\\Server->tickProcessor()
30.04 02:35:33 [Server] INFO #11 pmsrc/src/PocketMine(304): pocketmine\\Server->__construct(object BaseClassLoader#2, object pocketmine\\utils\\MainLogger#3, string[48] /, string[56] /plugins/)
30.04 02:35:33 [Server] INFO #12 pmsrc/src/PocketMine(327): pocketmine\\server()
30.04 02:35:33 [Server] INFO #13 pmsrc(11): require(string[92] phar:///PocketMine-MP.phar/src/Po)
30.04 02:35:33 [Server] INFO --- End of exception information ---
30.04 02:35:33 [Server] EMERGENCY An unrecoverable error has occurred and the server has crashed. Creating a crash dump
30.04 02:35:33 [Server] EMERGENCY Please upload the "/crashdumps/Sat_Apr_30-00.35.33-UTC_2022.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
30.04 02:35:33 [Server] EMERGENCY The crash dump has been automatically submitted to the Crash Archive. You can view it on https://crash.pmmp.io/view/6576453 or use the ID #6576453.

**Comment by suerion** [comment]
Why do you use not the file from announcement in discord, Branch is mot finished

**Comment by suerion** [comment]
fixed in #289
