### ISSUE TITLE
Plugin not working anymore

### ISSUE THREAD

**Issue by SillierShark195** [MihaiChirculete/WorldGuard#311]
The plugin not working anymore

**Comment by SillierShark195** [comment]
PocketMine-MP Crash Dump Sat May 20 22:08:19 UTC 2023

PocketMine-MP version: 4.21.0 [Protocol 582]
Git commit: ef40934d24748025d15d9b86acc28fbb82d6de6a
PHP version: 8.1.19
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: WorldGuard

Error: Implicit conversion from float 241.3763 to int loses precision
File: plugins/WorldGuard_dev-271.phar/src/MihaiChirculete/WorldGuard/WorldGuard
Line: 232
Type: ErrorException
Backtrace:
#0 plugins/WorldGuard_dev-271.phar/src/MihaiChirculete/WorldGuard/WorldGuard(232): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 8192, string[62] Implicit conversion from float 241.3763 to int loses precision, string[100] phar:///home/container/plugins/WorldGuard_dev-271.phar/src/MihaiChirculete/World, int 232)
#1 plugins/WorldGuard_dev-271.phar/src/MihaiChirculete/WorldGuard/WorldGuard(443): MihaiChirculete\WorldGuard\WorldGuard->getRegionNameFromPosition(object pocketmine\world\Position#49398)
#2 plugins/WorldGuard_dev-271.phar/src/MihaiChirculete/WorldGuard/EventListener(331): MihaiChirculete\WorldGuard\WorldGuard->updateRegion(object pocketmine\player\Player#30151)
#3 pmsrc/src/event/RegisteredListener(61): MihaiChirculete\WorldGuard\EventListener->onMove(object pocketmine\event\player\PlayerMoveEvent#51849)
#4 pmsrc/src/event/Event(63): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerMoveEvent#51849)
#5 pmsrc/src/player/Player(1333): pocketmine\event\Event->call()
#6 pmsrc/src/player/Player(1425): pocketmine\player\Player->processMostRecentMovements()
#7 pmsrc/src/world/World(1002): pocketmine\player\Player->onUpdate(int 4314)
#8 pmsrc/src/world/World(929): pocketmine\world\World->actuallyDoTick(int 4314)
#9 pmsrc/src/world/WorldManager(349): pocketmine\world\World->doTick(int 4314)
#10 pmsrc/src/Server(1803): pocketmine\world\WorldManager->tick(int 4314)
#11 pmsrc/src/Server(1685): pocketmine\Server->tick()
#12 pmsrc/src/Server(1068): pocketmine\Server->tickProcessor()
#13 pmsrc/src/PocketMine(336): pocketmine\Server->__construct(object BaseClassLoader#5, object pocketmine\utils\MainLogger#2, string[16] /home/container/, string[24] /home/container/plugins/)
#14 pmsrc/src/PocketMine(359): pocketmine\server()
#15 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by suerion** [comment]
The plugin is not maintained since 2022
