### ISSUE TITLE
Eror crash in pocketmine 4.21.0

### ISSUE THREAD

**Issue by NdaruAjaa** [MihaiChirculete/WorldGuard#312]
PocketMine-MP version: 4.21.0 [Protocol 582]
Git commit: ef40934d24748025d15d9b86acc28fbb82d6de6a
PHP version: 8.1.15
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: WorldGuard

Error: Implicit conversion from float 256.5126 to int loses precision
File: plugins/WorldGuard.phar/src/MihaiChirculete/WorldGuard/WorldGuard
Line: 230
Type: ErrorException
Backtrace:
#0 plugins/WorldGuard.phar/src/MihaiChirculete/WorldGuard/WorldGuard(230): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 8192, string[62] Implicit conversion from float 256.5126 to int loses precision, string[92] phar:///home/container/plugins/WorldGuard.phar/src/MihaiChirculete/WorldGuard/Wo, int 230)
#1 plugins/WorldGuard.phar/src/MihaiChirculete/WorldGuard/WorldGuard(441): MihaiChirculete\WorldGuard\WorldGuard->getRegionNameFromPosition(object pocketmine\world\Position#1174875)
#2 plugins/WorldGuard.phar/src/MihaiChirculete/WorldGuard/EventListener(323): MihaiChirculete\WorldGuard\WorldGuard->updateRegion(object pocketmine\player\Player#1105340)
#3 pmsrc/src/event/RegisteredListener(61): MihaiChirculete\WorldGuard\EventListener->onMove(object pocketmine\event\player\PlayerMoveEvent#1194919)
#4 pmsrc/src/event/Event(63): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerMoveEvent#1194919)
#5 pmsrc/src/player/Player(1333): pocketmine\event\Event->call()
#6 pmsrc/src/player/Player(1425): pocketmine\player\Player->processMostRecentMovements()
#7 pmsrc/src/world/World(1002): pocketmine\player\Player->onUpdate(int 111592)
#8 pmsrc/src/world/World(929): pocketmine\world\World->actuallyDoTick(int 111592)
#9 pmsrc/src/world/WorldManager(349): pocketmine\world\World->doTick(int 111592)
#10 pmsrc/src/Server(1803): pocketmine\world\WorldManager->tick(int 111592)
#11 pmsrc/src/Server(1685): pocketmine\Server->tick()
#12 pmsrc/src/Server(1068): pocketmine\Server->tickProcessor()
#13 pmsrc/src/PocketMine(336): pocketmine\Server->__construct(object BaseClassLoader#5, object pocketmine\utils\MainLogger#2, string[16] /home/container/, string[24] /home/container/plugins/)
#14 pmsrc/src/PocketMine(359): pocketmine\server()
#15 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by Driwen4356** [comment]
same error

**Comment by josusyai** [comment]
plugin fixed, check "https://github.com/josusyai/WorldGuard"

**Comment by NdaruAjaa** [comment]
@josusyai Thank You
